	<span data-action="toggle-nav" class="action nav-toggle">
		<span>Toggle Nav</span>
	</span>
	<a href="https://127.0.0.1/" class="logo" title aria-label="store logo">
		<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/Logo_icon_1.png')); ?>" alt="#"  />
	</a>
	<div class="header-phone">
		<span class="span">24/7 support</span>
		<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/header/phone_icon.png')); ?>" alt="#"  />
		<a class="span" href="tel:+1300999999">1300 999 999</a>
	</div>
	<div class="header-phone-mobile">
		<a href="tel:+1300999999">&nbsp;</a>
	</div>
