<div class="footer content">
	<div class="footer-wrapper">
		<div class="footer-wrapper-content">
			<div class="footer-top">
				<div class="content">
					<h4>We accept</h4>
					<div class="list-card">
						<ul>
							<li>
								<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/visa.jpg')); ?>" alt="#"  />
							</li>
							<li>
								<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/mastercard.png')); ?>" alt="#"  />
							</li>
							<li>
								<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/americanexpress.jpg')); ?>" alt="#"  />
							</li>
							<li>
								<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/paypal.jpg')); ?>" alt="#"  />
							</li>
							<li>
								<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/northernsecure.jpg')); ?>" alt="#"  />
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="footer-menu">
				<div class="ft-menu ft-customer">
					<h3>CoolRiver</h3>
					<ul>
						<li>
							<a href="https://127.0.0.1/About-Us">About Us</a>
						</li>
						<li>
							<a href="https://127.0.0.1/Products">Products</a>
						</li>
						<li>
							<a href="https://127.0.0.1/Vendors">Vendors</a>
						</li>
						<li>
							<a href="https://127.0.0.1/News-Events">News & Events</a>
						</li>
					</ul>
				</div>
				<div class="ft-menu ft-customer">
					<h3>Customer Support</h3>
					<ul>
						<li>
							<a href="https://127.0.0.1/contact-us">Contact Us</a>
						</li>
						<li>
							<a href="https://127.0.0.1/Support">Support</a>
						</li>
					</ul>
				</div>
				<div class="ft-menu ft-customer">
					<h3>Terms &amp; Privacy</h3>
					<ul>
						<li><a href="https://127.0.0.1/">Website Terms of Use</a></li>
						<li><a href="https://127.0.0.1/">Privacy Policy</a></li>
						<li><a href="https://127.0.0.1/">Customer Terms of Sale</a></li>
						<li><a href="https://127.0.0.1/">Delivery and returns</a></li>
					</ul>
				</div>
				<div class="ft-menu ft-customer">
					<h3>We accept</h3>
					<ul>
						<li>
							<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/Visa_icon.png')); ?>" alt="#"  />
						</li>
						<li>
							<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/Mastercard_icon.png')); ?>" alt="#"  />
						</li>
						<li>
							<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/AMEX_icon.png')); ?>" alt="#"  />
						</li>
						<li>
							<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/PayPal_icon.png')); ?>" alt="#"  />
						</li>
						<li>
							<img src="<?= $block->escapeUrl($block->getViewFileUrl('images/norton_icon.png')); ?>" alt="#"  />
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="footer-copyright">
	<div class="content">
		<div class="ft-left">
			<span class="span">ABN 00 000 000 000</span>
			<span class="span">ACN 000 000 000</span>
		</div>
		<div class="ft-right">
			<span class="span">1 Bourke Street, Melbourne, VIC 3000</span>
		</div>
	</div>
</div>